title: USGS targets tips and tricks
description: Overview of conventions and best practices for using targets in USGS Data Science workflows
template:
  repo: ds-pipelines-targets-2-template
  name: ds-pipelines-targets-2
before:
  - type: createIssue
    title: Overview of data science pipelines II
    body: 00-overview.md
    store:
      overview_issue_url: '{{ result.data.html_url }}'
steps:
  - title: Overview of data science pipelines II
    description: A refresher from pipelines I, and a hint of what is to come
    link: '{{ store.overview_issue_url }}'
    event: issues.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: Local setup
        body: 01-setup.md
        store:
          setup_issue_url: '{{ result.data.html_url }}'
  - title: Local setup
    description: Set up the code locally so that you are prepared to test functions and make changes
    link: '{{ store.setup_issue_url }}'
    event: issues.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: How to get past the gotchas without getting gotten again
        body: 10-scipiper-gotchas.md
        store:
          scipiper_gotchyas_url: '{{ result.data.html_url }}'
          scipiper_gotchyas_id: '{{ result.data.number }}'


# -- section 30 --- 
   
  - title: Overview of gotchas and best practices
    description: How to get past the gotchas without getting gotten again
    link: '{{ store.scipiper_gotchyas_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 11-targets-debug.md
        store:
          debug_url: '{{ result.data.html_url }}' 
  - title: Debugging in a targets pipeline
    description: How to inspect parts of the pipeline and variables within functions
    link: '{{ store.debug_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 12-visualize-pipeline.md
        store:
          visualize_url: '{{ result.data.html_url }}'    
  - title: Visualizing and understanding the status of dependencies in a pipeline
    description: How to inspect, view, and understand the state of pipeline targets with `tar_glimpse`
    link: '{{ store.visualize_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 13-target-status.md
        store:
          why_outdated_url: '{{ result.data.html_url }}'  
  - title: Using tar_visnetwork() for target status of pipeline targets
    description: How to inspect, view, and understand the state of pipeline targets with `tar_visnetwork` and `tar_outdated`
    link: '{{ store.why_outdated_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 14-cyclical-depends.md
        store:
          cyclical_url: '{{ result.data.html_url }}'           
  - title: What are cyclical dependencies and how to avoid them?
    description: Thinking in a directed network of dependencies is probably a new concept. It hurts the brain. How to avoid breaking the network with cyclical dependencies. 
    link: '{{ store.cyclical_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 15-undoc-file.md
        store:
          undoc_file_url: '{{ result.data.html_url }}' 
  - title: Creating side-effect targets or undocumented inputs
    description: If functions create outputs that aren't connected to the pipeline, they can get lost and cause unexpected issues. How and why to avoid creating side-effect targets. 
    link: '{{ store.undoc_file_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 16-dir-targets.md
        store:
          dir_targets_url: '{{ result.data.html_url }}'
  - title: How to depend on a directory for changes
    description: It is handy to "depend" on the contents of an entire directory, so that when anything changes, a target can be rebuilt.
    link: '{{ store.dir_targets_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 17-target-objects.md
        store:
          objects_url: '{{ result.data.html_url }}'  
  - title: Using non-target inputs in commands
    description: >- 
      We've been limited to using only target objects and files as inputs into pipeline functions. I want more! You'll get more here. 
    link: '{{ store.objects_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: closeIssue
        issue: '{{ store.scipiper_gotchyas_id }}'
      - type: createIssue
        title: Strategies for defining targets in data pipelines
        body: 20-many-targets.md
        store:
          many_targets_url: '{{ result.data.html_url }}'
          many_targets_id: '{{ result.data.number }}'
  - title: Strategies for defining targets in data pipelines
    description: >-
      Sometimes it is hard to figure out when something should be a tracked target vs an internal step of a longer-running function
    link: '{{ store.many_targets_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 21-target-expense.md
        store:
          target_expense_url: '{{ result.data.html_url }}'
  - title: Determining when to create a new target or merge existing targets
    description: Existing project examples that use pipelines; strategies for defining targets based on computational expense and re-use
    link: '{{ store.target_expense_url }}'
    event: issues.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: Refactor the existing pipeline to use more effective targets
        body: 22-target-refactor.md
        store:
          target_refactor_url: '{{ result.data.html_url }}'
          target_refactor_id: '{{ result.data.number }}'

  - title: Learn how to refactor an existing pipeline to use more effective targets
    description: A hands-on activity designed to expose the learner to decisions with targets
    link: '{{ store.target_refactor_url }}'
    event: pull_request.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: Learn the differences between different types of targets
        body: 30-target-kinds.md
        store:
          target_kinds_url: '{{ result.data.html_url }}'
          target_kinds_id: '{{ result.data.number }}'
      - type: closeIssue
        issue: '{{ store.target_refactor_id }}'
  - title: Object and file targets in pipelines
    description: Overview of different types of targets
    link: '{{ store.target_kinds_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 31-object-targets.md
        store:
          object_targets_url: '{{ result.data.html_url }}'
  - title: Pros and cons to using object targets
    description: When to choose R objects for pipeline targets
    link: '{{ store.object_targets_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 32-file-targets.md
        store:
          file_targets_url: '{{ result.data.html_url }}'          
  - title: Pros and cons to using file targets
    description: When to choose files for pipeline targets
    link: '{{ store.file_targets_url }}'
    event: issues.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: Exchange object and file targets in your pipelines
        body: 33-target-activity.md
        store:
          target_switch_url: '{{ result.data.html_url }}'
          target_switch_id: '{{ result.data.number }}'
  - title: Exchange object and file targets in your pipelines
    description: An assignment where you'll be asked to swap objects and files as targets
    link: '{{ store.target_switch_url }}'
    event: pull_request.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: datasci conventions
        body: 40-datasci-conventions.md
        store:
          target_conventions_url: '{{ result.data.html_url }}'
          target_conventions_id: '{{ result.data.number }}'
      - type: closeIssue
        issue: '{{ store.target_switch_id }}'     
  - title: Understanding USGS Data Science conventions and best practices
    description: Learn about some of the unique ways USGS DS likes to build their pipelines
    link: '{{ store.target_conventions_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 41-final-tips.md
        store:
          final_tips_url: '{{ result.data.html_url }}'
  - title: Final tips for being a smart pipeliner
    description: A few final notes about how to be strategic with your pipelines
    link: '{{ store.final_tips_url }}'
    event: issues.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: >-
          What's next
        body: 90-whats-next.md
      - type: closeIssue
        issue: '{{ store.final_tips_url }}'
